2021-05-30 11:26:43,679 ERROR: Exception on /login [GET] [in /home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py:1440]
Traceback (most recent call last):
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 2051, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1501, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/benc/Workspaces/microblog/app/routes.py", line 72, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/benc/Workspaces/microblog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/benc/Workspaces/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/home/benc/Workspaces/microblog/app/templates/login.html", line 27, in block 'content'
    <a href="{{ url_for('resetn_password_request') }}">Click to reset it</a>
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/helpers.py", line 334, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/helpers.py", line 321, in url_for
    rv = url_adapter.build(
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/werkzeug/routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'resetn_password_request'. Did you mean 'reset_password_request' instead?
2021-05-30 11:27:47,169 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:49]
2021-05-30 11:28:01,757 ERROR: Exception on /user/benc [GET] [in /home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py:1440]
Traceback (most recent call last):
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 2051, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1501, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/benc/Workspaces/microblog/app/routes.py", line 101, in user
    posts = user.posts.order_by(POst.timestamp.desc()).paginate(
NameError: name 'POst' is not defined
2021-05-30 11:28:20,091 ERROR: Exception on /user/benc [GET] [in /home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py:1440]
Traceback (most recent call last):
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 2051, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1501, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/benc/Workspaces/microblog/app/routes.py", line 101, in user
    posts = user.posts.order_by(POst.timestamp.desc()).paginate(
NameError: name 'POst' is not defined
2021-05-30 11:28:53,914 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:49]
2021-05-30 11:28:58,160 ERROR: Exception on /user/benc [GET] [in /home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py:1440]
Traceback (most recent call last):
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 2051, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1501, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/benc/Workspaces/microblog/app/routes.py", line 108, in user
    return render_template('user.html', user=user, posts=posts, form=form.items, \
AttributeError: 'EmptyForm' object has no attribute 'items'
2021-05-30 11:29:54,097 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:49]
2021-05-30 11:29:56,295 ERROR: Exception on /user/benc [GET] [in /home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py:1440]
Traceback (most recent call last):
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 2051, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1501, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/benc/Workspaces/microblog/app/routes.py", line 108, in user
    return render_template('user.html', user=user, posts=posts, form=form.item, \
AttributeError: 'EmptyForm' object has no attribute 'item'
2021-05-30 11:32:47,432 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:49]
2021-05-30 11:33:31,939 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:49]
