2021-05-30 11:33:36,032 ERROR: Exception on /user/benc [GET] [in /home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py:1440]
Traceback (most recent call last):
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 2051, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1501, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/benc/Workspaces/microblog/app/routes.py", line 108, in user
    return render_template('user.html', user=user, posts=posts, form=form, \
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/benc/Workspaces/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/benc/Workspaces/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/home/benc/Workspaces/microblog/app/templates/user.html", line 33, in block 'content'
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2021-05-30 11:36:02,007 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:49]
2021-05-30 11:36:20,997 ERROR: Exception on /reset_password_request [GET] [in /home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py:1440]
Traceback (most recent call last):
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 2051, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1501, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/benc/Workspaces/microblog/app/routes.py", line 99, in reset_password_request
    form = ResetPasswordRequestForm()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/wtforms/form.py", line 268, in __init__
    super(Form, self).__init__(self._unbound_fields, meta=meta_obj, prefix=prefix)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/wtforms/form.py", line 51, in __init__
    field = meta.bind_field(self, unbound_field, options)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/wtforms/meta.py", line 27, in bind_field
    return unbound_field.bind(form=form, **options)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/wtforms/fields/core.py", line 376, in bind
    return self.field_class(*self.args, **kw)
TypeError: __init__() got an unexpected keyword argument 'claidators'
2021-05-30 11:38:26,631 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:49]
2021-05-30 11:41:08,092 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:49]
2021-05-30 11:41:59,062 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:49]
2021-05-31 15:39:05,550 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:51]
2021-06-01 11:40:15,216 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:53]
2021-06-01 11:40:19,841 ERROR: Exception on /index [GET] [in /home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py:1440]
Traceback (most recent call last):
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 2051, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1501, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/benc/Workspaces/microblog/app/routes.py", line 37, in index
    return render_template('index.html', title='Home', form=form,
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/benc/Workspaces/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/benc/Workspaces/microblog/app/templates/base.html", line 55, in template
    {% end block %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'end'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2021-06-01 11:41:08,493 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:53]
2021-06-02 09:40:59,716 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:56]
2021-06-02 09:41:17,071 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:56]
2021-06-02 09:44:03,771 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:56]
2021-06-03 09:32:10,307 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:56]
2021-06-03 09:34:47,378 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:56]
2021-06-03 09:40:35,469 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:56]
2021-06-03 09:43:04,774 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:56]
2021-06-03 09:46:07,498 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:56]
2021-06-03 10:44:45,532 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:56]
2021-06-03 10:44:54,540 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:56]
2021-06-03 10:45:50,030 ERROR: Exception on /index [POST] [in /home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py:1440]
Traceback (most recent call last):
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 2051, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1501, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask/app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/benc/Workspaces/microblog/.venv-microblog/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/benc/Workspaces/microblog/app/routes.py", line 30, in index
    if language == 'UNKNOWN' or language > 5:
TypeError: '>' not supported between instances of 'str' and 'int'
2021-06-03 10:49:24,022 INFO: Microblog startup [in /home/benc/Workspaces/microblog/app/__init__.py:56]
